[package]
name = "wq"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
native_db = "0.8.2"
native_model = "0.4.20"
#native_model = { version = "0.6.2" }
serde = { version = "1.0.228", features = ["derive"] }
ulid = { version = "1.2.1", features = ["serde"] }
